### PR TITLE
[Depends/tvOS] Openssl Makefile

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Fixes the intermittent build issue

Puts target_platform check inside the iOS OS check to keep all iOS/tvOS in the one if check

### CODE REVIEW

**Comment by sy6sy2** [comment]
Thank you, what do think of this version of lines 15 to 22:

```makefile
ifeq ($(OS), ios)
  ifeq ($(TARGET_PLATFORM),appletvos)
    # Need to add "no-async" to avoid "'setcontext' is unavailable: not available on tvOS" error
    CONFIGURE=./Configure iphoneos-cross no-shared zlib no-asm no-async --prefix=$(PREFIX)
  else
    CONFIGURE=./Configure iphoneos-cross no-shared zlib no-asm --prefix=$(PREFIX)
  endif
endif
```

**Comment by fuzzard** [comment]
Yeah, agreed. streamlines everything nicely.

**Comment by sy6sy2** [comment]
Cool!
I will apply your merge and edit history of ATV-PR in order to keep correct commits order.

**Comment by fuzzard** [comment]
Feel free to just close this and do the update during your rebase. Wasnt sure when you would see this, so that was the only reason i PR'd it before i go to bed, haha.

**Comment by sy6sy2** [comment]
Ha ha, ok!
Thank you and good night ;-)

**Pull request closed without merging**
